### ISSUE TITLE
Extraction throws error "Support for the experimental syntax 'decorators-legacy' isn't currently enabled"

### ISSUE THREAD

**Issue by dyingangel666** [loclapp/locl#11]
I'm currently upgrading my angular 8 app to angular 9 and have to rewrite some code. In version 8 i already used the [i18n-polyfill](https://github.com/ngx-translate/i18n-polyfill) to translate and extract strings in my typescript code.

I've seen that i can now use $localize from @angular/localize to translate that stuff from my typescript files, but the build-in extraction tool doesn't recognize the translations in the typescript files, which leads my to this tool. But when i'm now running the extraction with following 
command:

`npx locl extract -s=src/app/**/*.ts -f=xlf -o=src/locales/messages.xlf`

i'm just receiving the following error:

```
> npx locl extract -s=src/app/**/*.ts -f=xlf -o=src/locales/messages.xlf

Extracting translations from "src/app/**/*.ts"
unknown: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (16:1):

> 16 | @Injectable({
     | ^
  17 |   providedIn: 'root',
  18 | })
  19 | export class AppSettingsService
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! headhunter-frontend@1.0.0 i18n:ts: `npx locl extract -s=src/app/**/*.ts -f=xlf -o=src/locales/messages.xlf`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the headhunter-frontend@1.0.0 i18n:ts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by ocombe** [comment]
Could you give me the content of your tsconfig file? I think there might be an issue there.

Also what version of Typescript do you use?

**Comment by hrzwkstim01** [comment]
I have a similar issue, when trying to extract from Typescript files, so I thought only .js are supported for now.

```
SyntaxError: unknown: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (5:1):

  3 | const name = '$localize';
  4 | 
> 5 | @Component({
    | ^
  6 |   selector: 'app-root',
  7 |   styleUrls: ['./app.component.scss'],
  8 |   templateUrl: './app.component.html'
    at Parser.raise (...\node_modules\@babel\parser\lib\index.js:7017:17)
    at Parser.expectOnePlugin (...\node_modules\@babel\parser\lib\index.js:8410:18)
    at Parser.parseDecorator (...\node_modules\@babel\parser\lib\index.js:10872:10)
    at Parser.parseDecorators (...\node_modules\@babel\parser\lib\index.js:10854:30)
    at Parser.parseStatement (...\node_modules\@babel\parser\lib\index.js:10687:12)
    at Parser.parseBlockOrModuleBlockBody (...\node_modules\@babel\parser\lib\index.js:11264:25)
    at Parser.parseBlockBody (...\node_modules\@babel\parser\lib\index.js:11251:10)
    at Parser.parseTopLevel (...\node_modules\@babel\parser\lib\index.js:10621:10)
    at Parser.parse (...\node_modules\@babel\parser\lib\index.js:12222:10)
    at parse (...\node_modules\@babel\parser\lib\index.js:12273:38) {
  pos: 71,
  loc: Position { line: 5, column: 0 },
  missingPlugin: [ 'decorators-legacy', 'decorators' ],
  code: 'BABEL_PARSE_ERROR'
}
```

Here my tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
```

Typescript version: 3.7.5

**Comment by DanielHabenicht** [comment]
I also have this issue. 
TSConfig:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "downlevelIteration": true,
    "module": "esnext",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "paths": {}
  }
}
```
Typescript 3.7.5

**Comment by cameronwaterman** [comment]
+1 on running into this issue. Also running Typescript 3.7.5.

Error:
```
Extracting translations from ".../src/**/*.ts"
...\node_modules\yargs\yargs.js:1172
      else throw err
           ^

SyntaxError: unknown: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (33:1):

  31 | };
  32 |
> 33 | @Component({
     | ^
  34 |     selector: 'filter',
  35 |     templateUrl: './filter.component.html',
  36 |     styleUrls: ['filter.component.scss'],
    at Parser._raise (...\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:723:17)
    at Parser.raiseWithData (...\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:716:17)
    at Parser.expectOnePlugin (...\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8621:18)
    at Parser.parseDecorator (...\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:11064:10)
    at Parser.parseDecorators (...\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:11046:30)
    at Parser.parseStatement (...\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:10879:12)
    at Parser.parseBlockOrModuleBlockBody (...\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:11456:25)
    at Parser.parseBlockBody (...\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:11443:10)
    at Parser.parseTopLevel (...\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:10813:10)
    at Parser.parse (...\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:12425:10)
```

tsconfig:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "downlevelIteration": true,
    "module": "esnext",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "data-view": [
        "dist/data-view"
      ],
      "data-view/*": [
        "dist/data-view/*"
      ]
    }
  }
}
```

**Comment by jonyadamit** [comment]
Same issue as others. Same tsconfig. Using typescript 3.8.3, Angular 9.1.0.   Fails upon `@Component` decorator.  
Any workarounds?

**Comment by vipex** [comment]
The extractor seems to work on the compiled, not localized, aot version of the application, not on the TS source code, so the correct use **should** be something like this:

```
ng build --prod --localize=false
npx locl extract -s=dist/**/*.ts -f=xlf -o=src/locales/messages.xlf
```

ref. [https://github.com/loclapp/locl/tree/master/libs/cli#usage](Usage)

**Comment by ocombe** [comment]
Thanks @vipex I missed that detail in their examples.
The extractor works on the compiled files, it's based on the one that the Angular team wrote, it uses a babel plugin to extract all `$localize` calls, and it only works on the js files.
The main reason for that is that template translations (the ones defined with the `i18n` attribute) are transformed into `$localize` calls by the `@angular/compiler`, and that only happens when the project is built.

And as @vipex mentioned, you need to build for `aot`, otherwise those `$localize` calls are not created (using `--prod` uses aot by default, but if you want a faster build you can just use `--aot` instead).

**Comment by kazeshini178** [comment]
@ocombe Curious are there plans to be able to target the source `.ts` files?
Curious as running `ng build --prod` before `locl extract` is a lot slower then run the `ng xi18n` command then using `locl extract` to merge the additional translations  (was looking at other issues)

As it seems `ng xi18n` doesnt perform a build to extract the translations
That being said I think locl output is a lot cleaner then xi18n

**Comment by ocombe** [comment]
@kazeshini178 you could only extract `$localize` calls inside of code on source files. It wouldn't work for templates because `$localize` function calls only exist in compiled templates.
If I'm not mistaken, `ng xi18n` is still using view engine extraction for now, it's not using ivy yet, that's why it's fast. It still requires a build but only superficial (it doesn't need to do all the steps like writing factory files).
