### ISSUE TITLE
Extract from library: Unexpected messageParts for `$localize` 

### ISSUE THREAD

**Issue by meriturva** [loclapp/locl#19]
First run with `locl` with our angular library.

So first I just added a localized string on template:
` <span class="h5 font-weight-bold" i18n="login|description@@layout.login">Login</span>`

I build library with ivy enabled (so no prod):
`ng build @aulos/layout-components`

then I run extract tool:
`npx locl extract -s=dist/aulos/layout-components/**/*.js -f=json -o=dist/i18n/en.json`

I just get always a babel error:

```
node_modules\@locl\cli\node_modules\yargs\yargs.js:1172
      else throw err
           ^

BabelParseError: unknown: Unexpected messageParts for `$localize` (expected an array of strings).
    at unwrapStringLiteralArray (D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\@locl\cli\src\cmds\extract\source_file_utils.js:138:15)
    at Object.unwrapMessagePartsFromLocalizeCall (D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\@locl\cli\src\cmds\extract\source_file_utils.js:91:27)
    at PluginPass.CallExpression (D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\@locl\cli\src\cmds\extract\source_files\es5_extract_plugin.js:19:62)
    at newFn (D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\@babel\core\node_modules\@babel\traverse\lib\visitors.js:179:21)
    at NodePath._call (D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:42:17)
    at NodePath.visit (D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.js:90:31)
    at TraversalContext.visitQueue (D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:112:16)
    at TraversalContext.visitSingle (D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:84:19)
    at TraversalContext.visit (D:\Projects\git.loccioni.com\web\loccioni-aulos-web\node_modules\@babel\core\node_modules\@babel\traverse\lib\context.js:140:19) {
  node: Node {
    type: 'LogicalExpression',
    start: 38151,
    end: 38442,
    loc: SourceLocation { start: [Position], end: [Position] },
    left: Node {
      type: 'Identifier',
      start: 38151,
      end: 38152,
      loc: [SourceLocation],
      name: 'Z',
      leadingComments: undefined,
      innerComments: undefined,
      trailingComments: undefined
    },
    operator: '||',
    right: Node {
      type: 'SequenceExpression',
      start: 38155,
      end: 38441,
      loc: [SourceLocation],
      expressions: [Array],
      extra: [Object],
      leadingComments: undefined,
      innerComments: undefined,
      trailingComments: undefined
    },
    leadingComments: undefined,
    innerComments: undefined,
    trailingComments: undefined
  },
  type: 'BabelParseError',
  code: 'BABEL_TRANSFORM_ERROR'
}
```

**Comment by ocombe** [comment]
Hello, sorry for the late answer.
You need to build for aot, so if you don't use prod you should at least use `--aot`.
If that doesn't fix your issue, let me know, but your span is extracted correctly for me locally.
