### ISSUE TITLE
"locl convert" error

### ISSUE THREAD

**Issue by rayita** [loclapp/locl#22]
I'm trying to conver translation files to json and I'm getting this error:

```
npx locl convert -s src/locale/messages.es.xlf -o src/assets/locale/

Converting files from source "F:\Projects\my-app\src\locale\messages.es.xlf" to format "json" and output "F:\Projects\my-app\src\assets\locale"
F:\my-app\node_modules\@locl\cli\node_modules\yargs\yargs.js:1172
      else throw err
           ^

TypeError: Cannot read property 'hasErrors' of undefined
    at F:\Projects\my-app\node_modules\@angular\localize\src\tools\src\translate\translation_files\translation_loader.js:49:41
    at Array.map (<anonymous>)
    at TranslationLoader.loadBundles (F:\Projects\my-app\node_modules\@angular\localize\src\tools\src\translate\translation_files\translation_loader.js:38:41)
    at convertFiles (F:\Projects\my-app\node_modules\@locl\cli\src\cmds\convert.js:57:50)
    at Object.exports.handler (F:\Projects\my-app\node_modules\@locl\cli\src\cmds\convert.js:36:5)
    at Object.runCommand (F:\Projects\my-app\node_modules\@locl\cli\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (F:\Projects\my-app\node_modules\@locl\cli\node_modules\yargs\yargs.js:1087:30)
    at Object.parse (F:\Projects\my-app\node_modules\@locl\cli\node_modules\yargs\yargs.js:575:25)
    at Object.<anonymous> (F:\Projects\my-app\node_modules\@locl\cli\src\main.js:24:6)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
```

The file i'm trying to conver is xlf format and is the translation of the one generated previously with Locl. It's is not a complex it's just a test with three lines of translations.

This is the file:

````
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en-US" datatype="plaintext" target-language="es">
    <body>
      <trans-unit id="LOGIN_BUTTON_LABEL" datatype="html">
        <source>Log in</source>
        <target>Login</target>
        <note priority="1" from="description">Login button label</note>
      </trans-unit>
      <trans-unit id="REGISTER_BUTTON_LABEL" datatype="html">
        <source>Register</source>
        <target>Registro</target>
        <note priority="1" from="description">Register button label</note>
      </trans-unit>
      <trans-unit id="APP_NAME" datatype="html">
        <source>Fleet</source>
        <target>Flota</target>
        <note priority="1" from="description">This is the name of the application</note>
        <note priority="1" from="meaning">Application name</note>
      </trans-unit>
    </body>
  </file>
</xliff>
````

**Comment by KamilBanaszkiewicz** [comment]
same issue

**Comment by ross-moug** [comment]
I'm also experiencing a similar problem with `locl convert`, trying to convert from `xlf` to `json`. Is there any update available on this issue?

**Comment by ds-twt** [comment]
Are there any updates regarding this issue?

**Comment by ocombe** [comment]
I was not able to repro this with Angular v10 or Angular v9.1.4.
Might have been something from v9.0 but the code is not compatible with that anymore.
