### ISSUE TITLE
Angular 10 support for convert

### ISSUE THREAD

**Issue by rapropos** [loclapp/locl#35]
[angular/angular 72f534f](https://github.com/angular/angular/commit/72f534f) seems to have changed the internal API that the convert tool relies on. I started writing a PR to fix this, but got stuck trying to figure out how to properly specify dependencies, and whether it is desired to split out a separate version or try to use a runtime check.

A runtime check that I think would be sufficient would be to check for the presence of `mergeBundles` in `TranslationLoader.prototype`. 

If it's present, two things have to happen in `convert.ts`:

* An initial `FileSystem` object needs to be passed to the `TranslationLoader` constructor. I simply fed it a `new NodeJSFileSystem()`.
* The `loadBundles` call needs two arrays; I gave it `([filesToProcess], [undefined])`.

Again, I apologize for not having enough knowledge to be able to evaluate how widely appropriate these fixes are, or to be able to package them into a usable PR. So I leave the observations here in the hopes that they may make some sort of contribution to the overall goal of allowing `locl` to work with Angular 10.

**Comment by ZNS** [comment]
Also ran into this issue in angular 10 when trying to convert from xlf to json. Same command works with angular 9.

```
D:\Jobb\Projekt\project5\project-frontend\node_modules\@locl\cli\node_modules\yargs\yargs.js:1172
      else throw err
           ^
TypeError: filePaths.map is not a function
    at TranslationLoader.mergeBundles (D:\Jobb\Projekt\project5\project-frontend\node_modules\@angular\localize\src\tools\src\translate\translation_files\translation_loader.js:101:37)
    at D:\Jobb\Projekt\project5\project-frontend\node_modules\@angular\localize\src\tools\src\translate\translation_files\translation_loader.js:51:30
    at Array.map (<anonymous>)
    at TranslationLoader.loadBundles (D:\Jobb\Projekt\project5\project-frontend\node_modules\@angular\localize\src\tools\src\translate\translation_files\translation_loader.js:49:41)
    at convertFiles (D:\Jobb\Projekt\project5\project-frontend\node_modules\@locl\cli\src\cmds\convert.js:57:50)       
    at Object.exports.handler (D:\Jobb\Projekt\project5\project-frontend\node_modules\@locl\cli\src\cmds\convert.js:36:5)
    at Object.runCommand (D:\Jobb\Projekt\project5\project-frontend\node_modules\@locl\cli\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] (D:\Jobb\Projekt\project5\project-frontend\node_modules\@locl\cli\node_modules\yargs\yargs.js:1087:30)
    at Object.parse (D:\Jobb\Projekt\project5\project-frontend\node_modules\@locl\cli\node_modules\yargs\yargs.js:575:25)
    at Object.<anonymous> (D:\Jobb\Projekt\project5\project-frontend\node_modules\@locl\cli\src\main.js:24:6)
```

**Comment by ocombe** [comment]
Hello, and thanks for the report.
Sorry for the delay, I've been very busy lately.
I'll start working on the fix.

**Comment by ocombe** [comment]
Ok I need this fix first https://github.com/angular/angular/pull/37977, once we have a new release of Angular I'll be able to fix the code to make it work with Angular 10

**Comment by JohannesHoppe** [comment]
Thanks for keeping us informed. I'm really looking forward to a fix! 👍

**Comment by helloworld121** [comment]
Hi Oliver, thank you so much for the fix. Do you already know when the next release will be? Thank you, Sebastian

**Comment by ocombe** [comment]
Hi, sorry for the delay, the new version was just released
